# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self
- submodules: true
#resources:
#  repositories:

jobs:
- template: azure-pipelines-build.yml  # Template reference
  parameters:
    name: MacOS
    pool:
      vmImage: 'macOS-10.13'
  steps:
  - displayName: 'setup'
    script: ./tools/setup.py
  - displayName: 'build'
    script: ./tools/build.py

- template: azure-pipelines-build.yml  # Template reference
  parameters:
    name: Linux
    pool:
      vmImage: 'ubuntu-16.04'
  steps:
  - displayName: 'setup'
    script: ./tools/setup.py
  - displayName: 'build'
    script: ./tools/build.py

- template: azure-pipelines-build.yml  # Template reference
  parameters:
    name: Windows
    pool:
      vmImage: 'vs2017-win2016'
  steps:
  - displayName: 'setup'
    script: ./tools/setup.py
  - displayName: 'build'
    script: ./tools/build.py

